name: jaguar_orm
description: Source-generated ORM with relations (one-to-one, one-to-many, many-to-many), preloading, cascading, polymorphic relations, etc
version: 2.2.7
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  jaguar_query: #^2.2.9
    path: ../query
  quiver: ^3.0.1
  path: ^1.8.0
  meta: ^1.3.0

dependency_overrides:
  jaguar_query:
    path: ../query

dev_dependencies:
  test: ^1.17.1
  jaguar_query_postgres: # ^0.2.5
    path: ../postgres

