import 'dart:async';
import 'package:jaguar_orm/jaguar_orm.dart';
import 'package:jaguar_orm/src/annotations/column.dart';
import 'package:jaguar_query_postgres/jaguar_query_postgres.dart';

part 'simple.jorm.dart';

const intArray = Array<int>(const Int());

class User {
  @Column(notNull: true, isPrimary: true)
  @auto
  int id;

  String name;

  @intArray
  List<int> scores;

  User({this.id, this.name, this.scores});

  bool operator ==(final other) {
    if (other is User) return id == other.id && name == other.name;
    return false;
  }

  @override
  int get hashCode => super.hashCode;

  String toString() => "User($id, $name, $scores)";
}

/// Bean logic is generated by Jaguar ORM
@GenBean()
class UserBean extends Bean<User> with _UserBean {
  UserBean(Adapter adapter) : super(adapter);

  String get tableName => 'simple_user';
}
