name: jaguar_query_sqflite
description: SQFLite adapter for jaguar_query
version: 2.2.6
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
- Aumard Jimmy <jimmy.aumard@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: '>=2.0.0-dev.65.0 <3.0.0'

flutter:

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.0.0
  jaguar_query: ^2.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  jaguar_query:
#    path: ../query
